version: "3.8"
services:
  app:
    build:
      context: . # Directory where your Dockerfile is located
    environment:
      SPRING_APPLICATION_NAME: student
      SPRING_DATASOURCE_NAME: studentsdb
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/studentsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nav@1234
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Nav@1234
      MYSQL_DATABASE: studentsdb
    ports:
      - "3306:3306"
