version: "3.9"
services:
  app:
    build:
      context: . # Directory where your Dockerfile is located
    environment:
      SPRING_APPLICATION_NAME: student
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/studentsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nav@1234
    ports:
      - "8000:8080" # Map port 8000 on host to port 8080 in the app container
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Nav@1234
      MYSQL_DATABASE: studentsdb
    ports:
      - "3307:3306" # Expose MySQL on the default port
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pNav@1234 || exit 1"]
      interval: 10s
      retries: 5

volumes:
  db-data: # Volume for persistent MySQL data
